### ISSUE TITLE
NdJson not being parsed

### ISSUE THREAD

**Issue by WannesFransen1994** [amrfaissal/ex_ndjson#1]
First of all thanks for this library. I'm trying to parse an NdJson from stdout (output from gherkin c implementation). I've tried writing it to a file as well, but this didn't help.

Here is the ndjson:
```
{"source":{"media":{"encoding":"UTF8","contentType":"text/x.cucumber.gherkin+plain"},"uri":"/home/wannes/Documents/temp/gherkin_parser/gherkin_c/testdata/good/minimal-example.feature","data":"Feature: Minimal\n\n  Example: minimalistic\n    Given the minimalism\n"}}
{"gherkinDocument":{"uri":"/home/wannes/Documents/temp/gherkin_parser/gherkin_c/testdata/good/minimal-example.feature","feature":{"language":"en","keyword":"Feature","name":"Minimal","location":{"line":1,"column":1},"children":[{"scenario":{"keyword":"Example","name":"minimalistic","location":{"line":3,"column":3},"steps":[{"keyword":"Given ","text":"the minimalism","location":{"line":4,"column":5}}]}}]}}}
{"pickle":{"uri":"/home/wannes/Documents/temp/gherkin_parser/gherkin_c/testdata/good/minimal-example.feature","language":"en","id":"93ce054b56a540becc47afcbe729ea7f87c74443","name":"minimalistic","locations":[{"line":3,"column":3}],"steps":[{"locations":[{"line":4,"column":11}],"text":"the minimalism"}]}}
``` 

If relevant, here is the output in string format (iex shell):

```
"{\"source\":{\"media\":{\"encoding\":\"UTF8\",\"contentType\":\"text/x.cucumber.gherkin+plain\"},\"uri\":\"/home/wannes/Documents/temp/gherkin_parser/gherkin_c/testdata/good/minimal-example.feature\",\"data\":\"Feature: Minimal\\n\\n  Example: minimalistic\\n    Given the minimalism\\n\"}}\n{\"gherkinDocument\":{\"uri\":\"/home/wannes/Documents/temp/gherkin_parser/gherkin_c/testdata/good/minimal-example.feature\",\"feature\":{\"language\":\"en\",\"keyword\":\"Feature\",\"name\":\"Minimal\",\"location\":{\"line\":1,\"column\":1},\"children\":[{\"scenario\":{\"keyword\":\"Example\",\"name\":\"minimalistic\",\"location\":{\"line\":3,\"column\":3},\"steps\":[{\"keyword\":\"Given \",\"text\":\"the minimalism\",\"location\":{\"line\":4,\"column\":5}}]}}]}}}\n{\"pickle\":{\"uri\":\"/home/wannes/Documents/temp/gherkin_parser/gherkin_c/testdata/good/minimal-example.feature\",\"language\":\"en\",\"id\":\"93ce054b56a540becc47afcbe729ea7f87c74443\",\"name\":\"minimalistic\",\"locations\":[{\"line\":3,\"column\":3}],\"steps\":[{\"locations\":[{\"line\":4,\"column\":11}],\"text\":\"the minimalism\"}]}}\n"
```

This output is able to be formatted by the "jq" linux program.
Elixir version: 1.10
OS: 18.04.1-Ubuntu

I am able to parse it manually though with the following code (though i am aware that this is definitely not best practices.):
```
output_string
    |> String.replace("}\n{", "}SPLIT HERE{")
    |> String.split("SPLIT HERE")
    |> Enum.map(&Jason.decode!/1)
```

Stacktrace (snipping string contents):
```
[error] GenServer ExNdjson.Worker terminating
** (UndefinedFunctionError) function nil.decode/1 is undefined
    nil.decode("{\"source\":{\"med [CONTENT SNIPPED] lism\\n\"}}")
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    (ex_ndjson 0.3.2) lib/ex_ndjson/parser.ex:39: ExNdjson.NdJSONParser.parse/1
    (ex_ndjson 0.3.2) lib/ex_ndjson/worker.ex:37: ExNdjson.Worker.handle_call/3
    (stdlib 3.12.1) gen_server.erl:661: :gen_server.try_handle_call/4
    (stdlib 3.12.1) gen_server.erl:690: :gen_server.handle_msg/6
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.411.0>): {:unmarshal, "{\"sourc [CONTENT SNIPPED] m\"}]}}\n"}
State: []
Client #PID<0.411.0> is alive

    (stdlib 3.12.1) gen.erl:167: :gen.do_call/4
    (elixir 1.10.3) lib/gen_server.ex:1020: GenServer.call/3
    (stdlib 3.12.1) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir 1.10.3) src/elixir.erl:278: :elixir.recur_eval/3
    (elixir 1.10.3) src/elixir.erl:263: :elixir.eval_forms/3
    (iex 1.10.3) lib/iex/evaluator.ex:258: IEx.Evaluator.handle_eval/5
    (iex 1.10.3) lib/iex/evaluator.ex:239: IEx.Evaluator.do_eval/3
    (iex 1.10.3) lib/iex/evaluator.ex:217: IEx.Evaluator.eval/3
** (exit) exited in: GenServer.call(ExNdjson.Worker, {:unmarshal, "{\"source\":{\"media\" [CONTENT SNIPPED]  }}\n"}, 5000)
    ** (EXIT) an exception was raised:
        ** (UndefinedFunctionError) function nil.decode/1 is undefined
            nil.decode("{\"source\":{\"media\":{\"encoding\":\"UTF8\",\"conten [CONTENT SNIPPED] m\\n\"}}")
            (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
            (ex_ndjson 0.3.2) lib/ex_ndjson/parser.ex:39: ExNdjson.NdJSONParser.parse/1
            (ex_ndjson 0.3.2) lib/ex_ndjson/worker.ex:37: ExNdjson.Worker.handle_call/3
            (stdlib 3.12.1) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib 3.12.1) gen_server.erl:690: :gen_server.handle_msg/6
            (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
    (elixir 1.10.3) lib/gen_server.ex:1023: GenServer.call/3

```

Thank you in advance for your support.

**Comment by amrfaissal** [comment]
@WannesFransen1994 Strange! Did you try to set `Jason` as your JSON library in your Mix config?
```
config :ex_ndjson, json_library: Jason
```

**Comment by WannesFransen1994** [comment]
Thank you for your response.

I did not. After adding this config, it worked. (kind of embarrassed here)

Would you be so kind to update this in the readme please? after reading the following line:
```
config :ex_ndjson, json_library: Poison # Defaults to Jason
```
I mistakenly assumed that even without adding this, it'd default to Jason. Thank you once again for this library!

Regards

**Comment by amrfaissal** [comment]
No problem!
Good point, I need to adapt the code to fallback to `Jason` by default in case `Application.get_env` returns `nil` which is why your call was crashing.

Feel free to raise a PR if you got some spare time.
